# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["komuro@fastly.com"]
description = ""
language = "javascript"
manifest_version = 3
name = "rsc-demo-edge-backend"
service_id = ""

[local_server]

  [local_server.backends]

  [local_server.kv_stores]

    [[local_server.kv_stores.my-app-data]]
      data = "dummy"
      key = "dummy"

[setup]

  [setup.kv_stores]

    [setup.kv_stores.my-app-data]
      description = "KV Store for App Data"

[scripts]
  build = "npm run build"
